In [83]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.11/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2025.1.31)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [84]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
statlog_german_credit_data = fetch_ucirepo(id=144)

# data (as pandas dataframes)
X = statlog_german_credit_data.data.features
y = statlog_german_credit_data.data.targets

# metadata
print(statlog_german_credit_data.metadata)

# variable information
print(statlog_german_credit_data.variables)

{'uci_id': 144, 'name': 'Statlog (German Credit Data)', 'repository_url': 'https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data', 'data_url': 'https://archive.ics.uci.edu/static/public/144/data.csv', 'abstract': 'This dataset classifies people described by a set of attributes as good or bad credit risks. Comes in two formats (one all numeric). Also comes with a cost matrix', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1000, 'num_features': 20, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Other', 'Marital Status', 'Age', 'Occupation'], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1994, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5NC77', 'creators': ['Hans Hofmann'], 'intro_paper': None, 'additional_info': {'summary': 'Two datasets are provided.  the original dataset, in the form provided by Prof. Hofmann, contains categorical/symbolic attributes and is in the file "german.data".   \r\n \r\nFor algorithms that need numerical attributes, Strathclyde University produced the file "german.data-numeric".  This file has been edited and several indicator variables added to make it suitable for algorithms which cannot cope with categorical variables.   Several attributes that are ordered categorical (such as attribute 17) have been coded as integer.    This was the form used by StatLog.\r\n\r\nThis dataset requires use of a cost matrix (see below)\r\n\r\n ..... 1        2\r\n----------------------------\r\n  1   0        1\r\n-----------------------\r\n  2   5        0\r\n\r\n(1 = Good,  2 = Bad)\r\n\r\nThe rows represent the actual classification and the columns the predicted classification.\r\n\r\nIt is worse to class a customer as good when they are bad (5), than it is to class a customer as bad when they are good (1).\r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Attribute 1:  (qualitative)      \r\n Status of existing checking account\r\n             A11 :      ... <    0 DM\r\n\t       A12 : 0 <= ... <  200 DM\r\n\t       A13 :      ... >= 200 DM / salary assignments for at least 1 year\r\n               A14 : no checking account\r\n\r\nAttribute 2:  (numerical)\r\n\t      Duration in month\r\n\r\nAttribute 3:  (qualitative)\r\n\t      Credit history\r\n\t      A30 : no credits taken/ all credits paid back duly\r\n              A31 : all credits at this bank paid back duly\r\n\t      A32 : existing credits paid back duly till now\r\n              A33 : delay in paying off in the past\r\n\t      A34 : critical account/  other credits existing (not at this bank)\r\n\r\nAttribute 4:  (qualitative)\r\n\t      Purpose\r\n\t      A40 : car (new)\r\n\t      A41 : car (used)\r\n\t      A42 : furniture/equipment\r\n\t      A43 : radio/television\r\n\t      A44 : domestic appliances\r\n\t      A45 : repairs\r\n\t      A46 : education\r\n\t      A47 : (vacation - does not exist?)\r\n\t      A48 : retraining\r\n\t      A49 : business\r\n\t      A410 : others\r\n\r\nAttribute 5:  (numerical)\r\n\t      Credit amount\r\n\r\nAttibute 6:  (qualitative)\r\n\t      Savings account/bonds\r\n\t      A61 :          ... <  100 DM\r\n\t      A62 :   100 <= ... <  500 DM\r\n\t      A63 :   500 <= ... < 1000 DM\r\n\t      A64 :          .. >= 1000 DM\r\n              A65 :   unknown/ no savings account\r\n\r\nAttribute 7:  (qualitative)\r\n\t      Present employment since\r\n\t      A71 : unemployed\r\n\t      A72 :       ... < 1 year\r\n\t      A73 : 1  <= ... < 4 years  \r\n\t      A74 : 4  <= ... < 7 years\r\n\t      A75 :       .. >= 7 years\r\n\r\nAttribute 8:  (numerical)\r\n\t      Installment rate in percentage of disposable income\r\n\r\nAttribute 9:  (qualitative)\r\n\t      Personal status and sex\r\n\t      A91 : male   : divorced/separated\r\n\t      A92 : female : divorced/separated/married\r\n              A93 : male   : single\r\n\t      A94 : male   : married/widowed\r\n\t      A95 : female : single\r\n\r\nAttribute 10: (qualitative)\r\n\t      Other debtors / guarantors\r\n\t      A101 : none\r\n\t      A102 : co-applicant\r\n\t      A103 : guarantor\r\n\r\nAttribute 11: (numerical)\r\n\t      Present residence since\r\n\r\nAttribute 12: (qualitative)\r\n\t      Property\r\n\t      A121 : real estate\r\n\t      A122 : if not A121 : building society savings agreement/ life insurance\r\n              A123 : if not A121/A122 : car or other, not in attribute 6\r\n\t      A124 : unknown / no property\r\n\r\nAttribute 13: (numerical)\r\n\t      Age in years\r\n\r\nAttribute 14: (qualitative)\r\n\t      Other installment plans \r\n\t      A141 : bank\r\n\t      A142 : stores\r\n\t      A143 : none\r\n\r\nAttribute 15: (qualitative)\r\n\t      Housing\r\n\t      A151 : rent\r\n\t      A152 : own\r\n\t      A153 : for free\r\n\r\nAttribute 16: (numerical)\r\n              Number of existing credits at this bank\r\n\r\nAttribute 17: (qualitative)\r\n\t      Job\r\n\t      A171 : unemployed/ unskilled  - non-resident\r\n\t      A172 : unskilled - resident\r\n\t      A173 : skilled employee / official\r\n\t      A174 : management/ self-employed/\r\n\t\t     highly qualified employee/ officer\r\n\r\nAttribute 18: (numerical)\r\n\t      Number of people being liable to provide maintenance for\r\n\r\nAttribute 19: (qualitative)\r\n\t      Telephone\r\n\t      A191 : none\r\n\t      A192 : yes, registered under the customers name\r\n\r\nAttribute 20: (qualitative)\r\n\t      foreign worker\r\n\t      A201 : yes\r\n\t      A202 : no\r\n', 'citation': None}}
           name     role         type     demographic  \
0    Attribute1  Feature  Categorical            None
1    Attribute2  Feature      Integer            None
2    Attribute3  Feature  Categorical            None
3    Attribute4  Feature  Categorical            None
4    Attribute5  Feature      Integer            None
5    Attribute6  Feature  Categorical            None
6    Attribute7  Feature  Categorical           Other
7    Attribute8  Feature      Integer            None
8    Attribute9  Feature  Categorical  Marital Status
9   Attribute10  Feature  Categorical            None
10  Attribute11  Feature      Integer            None
11  Attribute12  Feature  Categorical            None
12  Attribute13  Feature      Integer             Age
13  Attribute14  Feature  Categorical            None
14  Attribute15  Feature  Categorical           Other
15  Attribute16  Feature      Integer            None
16  Attribute17  Feature  Categorical      Occupation
17  Attribute18  Feature      Integer            None
18  Attribute19  Feature       Binary            None
19  Attribute20  Feature       Binary           Other
20        class   Target       Binary            None

                                          description   units missing_values
0                 Status of existing checking account    None             no
1                                            Duration  months             no
2                                      Credit history    None             no
3                                             Purpose    None             no
4                                       Credit amount    None             no
5                               Savings account/bonds    None             no
6                            Present employment since    None             no
7   Installment rate in percentage of disposable i...    None             no
8                             Personal status and sex    None             no
9                          Other debtors / guarantors    None             no
10                            Present residence since    None             no
11                                           Property    None             no
12                                                Age   years             no
13                            Other installment plans    None             no
14                                            Housing    None             no
15            Number of existing credits at this bank    None             no
16                                                Job    None             no
17  Number of people being liable to provide maint...    None             no
18                                          Telephone    None             no
19                                     foreign worker    None             no
20                                  1 = Good, 2 = Bad    None             no

In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [86]:
X = pd.DataFrame(X)
X.columns = ['Status', 'Duration', 'CreditHistory', 'Purpose', 'CreditAmount', 'Savings', 'Employment', 'InstallmentRate', 'SexMaritalStatus', 'Guarantors', 'ResidenceSince', 'Property', 'Age', 'OtherDebtors', 'Housing','NoOfCredits', 'Job','Responsibilities', 'Telephone', 'ForeignWorker']

X.head()

,Status,Duration,CreditHistory,Purpose,CreditAmount,Savings,Employment,InstallmentRate,SexMaritalStatus,Guarantors,ResidenceSince,Property,Age,OtherDebtors,Housing,NoOfCredits,Job,Responsibilities,Telephone,ForeignWorker
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,4,A121,67,A143,A152,2,A173,1,A192,A201
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,2,A121,22,A143,A152,1,A173,1,A191,A201
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,3,A121,49,A143,A152,1,A172,2,A191,A201
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,4,A122,45,A143,A153,1,A173,2,A191,A201
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,4,A124,53,A143,A153,2,A173,2,A191,A201

In [87]:
attribute1 = {
    #status
   'A11' :  'Less than0 DM',
	'A12': '0 to 200 DM',
    'A13':  'salary assignments for at least 1 year',
    'A14' : 'no checking account'
}
attribute2 = {
    #credit history
     'A30' : 'no credits taken/all credits paid back duly',
    'A31' : 'all credits at this bank paid back duly',
    'A32' : 'existing credits paid back duly',
    'A33' : 'delay in paying off in the past',
    'A34' : 'critical account/other credits existing (not at this bank)'
}
attribute3 = {
    #purpose
    'A40' : 'car (new)',
    'A41' : 'car (used)',
    'A42' : 'furniture/equipment',
    'A43' : 'radio/television',
    'A44' : 'domestic appliances',
    'A45' : 'repairs',
    'A46' : 'education',
    'A47' : 'vacation',
    'A48' : 'retraining',
    'A49' : 'business',
    'A410' : 'others'
}
attribute4 = {
    #savings account/bonds
    'A61' :  'Less than 100 DM',
    'A62' :  '100 to 500 DM',
    'A63' :   '500 to 1000 DM',
	'A64' :   'Greater than 1000 DM',
    'A65' :   'unknown/ no savings account'

}

attribute5 = {
    #Present employment since
    'A71' : 'unemployed',
    'A72' :  'Less than 1 year',
    'A73' : '1 to 4 years ',
    'A74' : '4 to 7 years',
    'A75' : 'Greater than 7 years'

}

attribute6 = {
    #sex and marital status
    'A91' : 'male divorced/separated',
	'A92' : 'female divorced/separated/married',
    'A93' : 'male single',
	'A94' : 'male married/widowed',
	'A95' : 'female single'
}

attribute7 = {
    #Other debtors / guarantors
    'A101' : 'none',
    'A102' : 'co-applicant',
    'A103' : 'guarantor'
}
attribute8 = {
    #Property
    'A121' : 'real estate',
	'A122' : 'if not A121 building society savings agreement/life insurance',
    'A123' : 'if not A121/A122 car or other not in attribute 6',
	'A124' : 'unknown / no property'
}
attribute9 = {
    #Other installment plans
     'A141' : 'bank',
     'A142' : 'stores',
    'A143' : 'none'
}

attribute10 = {
    #Housing
    'A151' : 'rent',
    'A152' : 'own',
    'A153' : 'for free'
}

attribute11 = {
    #Job
    'A171' : 'unemployed/ unskilled  - non-resident',
    'A172' : 'unskilled - resident',
    'A173' : 'skilled employee / official',
    'A174' : 'management/ self-employed/highly qualified employee/ officer'
}

attribute12 = {
    #telephone
    'A191' : 'none',
   'A192' : 'yes, registered under the customers name'
}

attribute13 = {
    #foreign worker
    'A201' : 'yes',
    'A202' : 'no'
}

X = X.replace({'Status': attribute1, 'CreditHistory': attribute2, 'Purpose': attribute3, 'Savings': attribute4, 'Employment': attribute5, 'SexMaritalStatus': attribute6, 'Guarantors': attribute7, 'Property': attribute8, 'OtherDebtors': attribute9, 'Housing': attribute10, 'Job': attribute11, 'Telephone': attribute12, 'ForeignWorker': attribute13})
X.head()

,Status,Duration,CreditHistory,Purpose,CreditAmount,Savings,Employment,InstallmentRate,SexMaritalStatus,Guarantors,ResidenceSince,Property,Age,OtherDebtors,Housing,NoOfCredits,Job,Responsibilities,Telephone,ForeignWorker
0,Less than0 DM,6,critical account/other credits existing (not a...,radio/television,1169,unknown/ no savings account,Greater than 7 years,4,male single,none,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,0 to 200 DM,48,existing credits paid back duly,radio/television,5951,Less than 100 DM,1 to 4 years,2,female divorced/separated/married,none,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,no checking account,12,critical account/other credits existing (not a...,education,2096,Less than 100 DM,4 to 7 years,2,male single,none,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,Less than0 DM,42,existing credits paid back duly,furniture/equipment,7882,Less than 100 DM,4 to 7 years,2,male single,guarantor,4,if not A121 building society savings agreement...,45,none,for free,1,skilled employee / official,2,none,yes
4,Less than0 DM,24,delay in paying off in the past,car (new),4870,Less than 100 DM,1 to 4 years,3,male single,none,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

In [88]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Status            1000 non-null   object
 1   Duration          1000 non-null   int64
 2   CreditHistory     1000 non-null   object
 3   Purpose           1000 non-null   object
 4   CreditAmount      1000 non-null   int64
 5   Savings           1000 non-null   object
 6   Employment        1000 non-null   object
 7   InstallmentRate   1000 non-null   int64
 8   SexMaritalStatus  1000 non-null   object
 9   Guarantors        1000 non-null   object
 10  ResidenceSince    1000 non-null   int64
 11  Property          1000 non-null   object
 12  Age               1000 non-null   int64
 13  OtherDebtors      1000 non-null   object
 14  Housing           1000 non-null   object
 15  NoOfCredits       1000 non-null   int64
 16  Job               1000 non-null   object
 17  Responsibilities  1000 non-null   int64
 18  Telephone         1000 non-null   object
 19  ForeignWorker     1000 non-null   object
dtypes: int64(7), object(13)
memory usage: 156.4+ KB

In [89]:
X['InstallmentRate'].value_counts()

InstallmentRate
4    476
2    231
3    157
1    136
Name: count, dtype: int64

In [90]:
y = y.replace({1: True, 2: False})
y.head()
print(type(y))
y.info()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   class   1000 non-null   bool
dtypes: bool(1)
memory usage: 1.1 KB

<ipython-input-90-23250769f77d>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({1: True, 2: False})

In [91]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import tree

In [92]:
X = pd.get_dummies(X, columns=['Status', 'CreditHistory', 'Purpose', 'Savings', 'Employment', 'SexMaritalStatus', 'Guarantors', 'Property', 'OtherDebtors', 'Housing', 'Job', 'Telephone', 'ForeignWorker'],dtype=float)


x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = tree.DecisionTreeClassifier()
model= model.fit(x_train, y_train)


y_pred = model.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 31  28]
 [ 28 113]]
              precision    recall  f1-score   support

       False       0.53      0.53      0.53        59
        True       0.80      0.80      0.80       141

    accuracy                           0.72       200
   macro avg       0.66      0.66      0.66       200
weighted avg       0.72      0.72      0.72       200